---
title: "O2"
format:
  html:
    toc: true
---

> Working with the HMS O2 cluster


O2 status: [O2 Status](https://harvardmed.atlassian.net/wiki/spaces/O2/pages/1600651306/O2+Cluster+Status){target="_blank"} \
[More Information on the O2 Cluster](https://harvardmed.atlassian.net/wiki/spaces/O2/overview){target="_blank"} \


## Setting up your O2 account

### Obtain your O2 account
[Info](https://harvardmed.atlassian.net/wiki/spaces/O2/pages/1918304257/How+to+request+or+retain+an+O2+account){target="_blank"} \

### Getting on O2
Using your computer's terminal, use the following command to access O2 and enter your credentials accordingly.

```{python}
#| eval: false
ssh (hms_username)@o2.hms.harvard.edu

```


### Requesting access to the /n/groups/kwon/ groups folder

To request access, email `rchelp@hms.harvard.edu` to ask for access to the group folder /n/groups/kwon on O2. Please copy dkwon@mgh.harvard.edu and jelsherbini@mgh.harvard.edu. 


### Making a scratch directory.

Note, files on the scratch directory are automatically deleted **45 days** after their last modificaiton date. This is only for **TEMPORARY STORAGE**. Everything you want to keep needs to be moved to your folder in /n/groups/kwon/(your name).

**(On the login node)** Run the following on O2: /n/cluster/bin/scratch_create_directory.sh


### Get Duo Push for Android / IOS  and register with HMS

- Download the app : https://it.hms.harvard.edu/duo-mobile-app
- Email [itservicedesk@hms.harvard.edu](mailto:itservicedesk@hms.harvard.edu). or call 617-432-2000 to ask HMS IT to get registered with Duo


### Setting up 2-Factor Authentication

To set default 2-factor authentication option to call or push: \
For push (recommended, but only if you already have Duo push!):
```{python}
#| eval: false
echo 'export DUO_PASSCODE=push' >> $HOME/.bashrc
```
For phone
```{python}
#| eval: false
echo 'export DUO_PASSCODE=phone' >> $HOME/.bashrc
```
DO NOT set text as your default

### Setup passwordless login (ssh keys):
To set passwordless login, follow the SSH keys tutorial [here](https://harvardmed.atlassian.net/wiki/spaces/O2/pages/1600651365/How+to+Generate+SSH+Keys){target="_blank"} \





\
\
