---
title: "R workshop"
format:
  html:
    toc: true
---

```{r}
#| echo: false
#| warning: false
#| message: false

library(countdown)
library(tidyverse)
library(cowplot)
library(colorspace)
library(here)

metadata <- read_csv(here::here("datasets/metadata.csv"))
plate_1 <- read_csv(here::here("datasets/plate_1_data.csv"))
plate_2 <- read_csv(here::here("datasets/plate_2_data.csv"))
plate_3 <- read_csv(here::here("datasets/plate_3_data.csv"))
plate_4 <- read_csv(here::here("datasets/plate_4_data.csv"))

all_plate_data <- bind_rows(plate_1, plate_2, plate_3, plate_4)

joined_data <- all_plate_data %>%
  left_join(metadata)

media_background <- joined_data %>%
  filter(bug == "CTRL") 

media_background_medians <- media_background %>%
  group_by(plate_id, condition, conc) %>%
  summarise(no_bacteria_control = median(od))

bug_no_lcfa_control <- joined_data %>%
  filter(condition == "CTRL") %>%
  filter(bug != "CTRL") %>%
  left_join(media_background_medians) %>%
  mutate(background_subtracted_od = od - no_bacteria_control)
  
bug_no_lcfa_control_medians <- bug_no_lcfa_control %>%
  group_by(plate_id, bug) %>%
  summarise(no_lcfa_control = median(background_subtracted_od)) %>%
  ungroup()

relative_growths <- joined_data %>%
  filter(condition != "CTRL", bug !="CTRL") %>%
  left_join(media_background_medians) %>%
  mutate(background_subtracted_od = od - no_bacteria_control) %>%
  left_join(bug_no_lcfa_control_medians) %>%
  mutate(relative_growth = background_subtracted_od/ no_lcfa_control) 
```

> Learn how to use RStudio and the `tidyverse` for data exploration


## Slides: Intro to RStudio, Quarto, and R
[Make slides full screen](slides.qmd)

```{=html}
<iframe class="slide-deck" src="slides.html" height="420" width="747" style="border: 1px solid #2e3846;"></iframe>
```

## Download the instructional dataset:

The main data set for use in lectures is split into 5 tables. The idea of this dataset is that there is a randomized controlled trial of a drug aimed at reducing HIV risk by reducing inflammation. There were 23 participants in the placebo arm and 21 in the treatment arm. There were 3 visits for the trial – baseline (before any treatment occurred), week_1 (1 week after treatment) and week_7 (7 weeks after treatment). At each time point inflammation was measured using luminex (elisa_cytokines table) and immune cells counts were measured from a pap-smear (flow_cytometry table).  

- [`00_sample_ids.csv`](datasets/instructional_dataset/00_sample_ids.csv)

`pid` – participant id  
`time_point` – “baseline”, “week_1”, or “week_7” 
`arm` – “treatment” or “placebo"  
`sample_id` – the “wet-lab” sample id associated with this timepoint  

- [`01_participant_metadata.csv`](datasets/instructional_dataset/01_participant_metadata.csv)

`pid` - participant id  
`arm` - “treatment” or “placebo”  
`smoker` - “yes” or “no”  
`age` – age in years  
`education` – 4 options (“less than grade 9”, "grade 10-12, not matriculated", "grade 10-12, matriculated", "post-secondary")  
`sex` – all participants are “Female”  

- [`02_visit_clinical_measurements.csv`](datasets/instructional_dataset/02_visit_clinical_measurements.csv)

`pid` – particpant id  
`time_point` – “baseline”, “week_1”, or “week_7”  
`arm` – “treatment” or “placebo”  
`nugent_score` – [Nugent Score](https://en.wikipedia.org/wiki/Nugent_score), a number from 0-10. 0-3 is no BV, 4-6 is intermediate BV, and 7-10 is BV  .
`crp_blood` – decimal number representing C-reactive protein blood test (CRP) 
`ph` – vaginal pH  

- [`03_elisa_cytokines.csv`](datasets/instructional_dataset/03_elisa_cytokines.csv)

`sample_id` - the “wet-lab” sample id associated with this timepoint  
`cytokine` - "IL-1a", "IL-10", "IL-1b", "IL-8", "IL-6", "TNFa", "IP-10", "MIG", "IFN-Y", "MIP-3a"  
`conc` – decimal number representing concentration   
`limits` – either “within limits” or “out of range” 

- [`04_flow_cytometry.csv`](datasets/instructional_dataset/04_flow_cytometry.csv)

`sample_id` - the “wet-lab” sample id associated with this timepoint  
All other columns – the integer count of this type of cell in this sample

`cd4_t_cells` might best be analyzed as a proportion of `cd3_t_cells`...
### Read in data

Data is often in tables, and the easiest way to store tabular data is in `csv` or `tsv` format.

`csv` - comma separated values    
`tsv` - tab separated values  

to read in data stored this way use `read_csv(filename)` or `read_tsv(filename)`


{{< include _03_tidyverse_exercise.qmd >}}


{{< include _01_pen_and_paper.qmd >}}


{{< include _02_ggplot_exercise.qmd >}}

{{< include _04_data_wrangling_2.qmd >}}


## Advanced next steps

Join together the cytokine data and the metadata and explore the relationships between timepoint, arm, and the different cytokines.

Note, to do this you will need to use [`00_sample_ids.csv`](datasets/instructional_dataset/00_sample_ids.csv), [`01_participant_metadata.csv`](datasets/instructional_dataset/01_participant_metadata.csv), and [`03_elisa_cytokines.csv`](datasets/instructional_dataset/03_elisa_cytokines.csv) . 

Also look at the relationship of vaginal pH to the different cytokines. Now you'll need to join the [`02_visit_clinical_measurements.csv`](datasets/instructional_dataset/02_visit_clinical_measurements.csv) table as well.